# Deploy Blazor Kawaii demo to GitHub Pages

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4

      # Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # Install .NET WebAssembly Tools
      - name: Install .NET WebAssembly Tools
        run: dotnet workload install wasm-tools

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build -c Release --no-restore

      # Publish the site
      - name: Publish
        run: dotnet publish Demo/Demo.csproj -c:Release -o:publish -p:GHPages=true

      # Deploy the site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish/wwwroot
          force_orphan: true
          cname: blazorkawaii.example.com # Optional: Add your custom domain here if you have one